### ISSUE TITLE
ACL Anthologyのバッチも稼働しよう．

### ISSUE THREAD

**Issue by wanted2** [wanted2/caineng.in#536]
@nitta-aifi ACL Anthologyのバッチも稼働しよう．

_Originally posted by @wanted2 in https://github.com/wanted2/caineng.in/discussions/392#discussioncomment-2275050_

**Comment by wanted2** [comment]
@nitta-aifi 年数回しかやらないなら `workflow_dispatch` で手動でも十分だよ．
好きな時にGithubActionsのUIで実行すればいいじゃないの？

年数回しかないだろう．

**Comment by nitta-aifi** [comment]
@wanted2 なるほど．CVFのバッチもそうですね．

**Comment by wanted2** [comment]
そうそう，年数回しかないので， `workflow_dispatch`で好きな時に実行すればいいんだよ．

**Comment by nitta-aifi** [comment]
なるほどです．`workflow_dispatch`を設ければ，GithubActionsにログを残すため，実行歴も見れますね．

まあ，確かに年一度しかないイベントもあるから，毎日実行しても意味ないですね．
