### ISSUE TITLE
なるほど，ちょっと引用数を増やしてもいいと思います．どこまで増やすか諸君が活発に貢献できるように制度とかルールを向上したいですが，コンパイル時間も短縮したいですね．

### ISSUE THREAD

**Issue by wanted2** [wanted2/caineng.in#547]
@nitta-aifi なるほど，ちょっと引用数を増やしてもいいと思います．どこまで増やすか諸君が活発に貢献できるように制度とかルールを向上したいですが，コンパイル時間も短縮したいですね．

引用の種類ですが，通常の`article`,`book`,`inproceedings`,`incollection`,`thesis`などはいいけれどもね．ですが，`misc`などでURLを引用したい場合，直接に`a`タグとか，`footnote`を使ってほしいです．いかがでしょうか？

_Originally posted by @wanted2 in https://github.com/wanted2/caineng.in/discussions/546#discussioncomment-2298992_

**Comment by wanted2** [comment]
@nitta-aifi いろいろと検討した結果，

- 引用数は最大7個
- 読む分数を最大40m

まあ，引用数はブログなので，そんなにいらないだろうという論があるため，分数だけですね，増やします．

40m程度で十分ですね．

**Comment by nitta-aifi** [comment]
@wanted2 CC: @aifi-inc

承知いたしました。 🙇
