### ISSUE TITLE
Change profile page

### ISSUE THREAD

**Issue by wanted2** [wanted2/caineng.in#613]
**Is your feature request related to a problem? Please describe.**

プロフィールページをもう少しきれいにしましょう．

- [x] **趣味**
- [x] **週末でやっていること**：最近は「お金について夢中に考えてているばかり「とかでもいいです．正直に言えばいいですね．

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nitta-aifi** [comment]
@wanted2 お金ではにですね！正確にいうと「米ドル＄」ですね． 😄 😄 😄

**Comment by wanted2** [comment]
@nitta-aifi 君，そうですね．ばっちりですね．「米ドル＄「ですね．

**Comment by nitta-aifi** [comment]
お金はいらないです．米ドル＄が必要ですね．

**Comment by wanted2** [comment]
賛成です．お金がいらなく，米ドルだけが必要です．
